name: healthapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  ionicons : ^0.2.1
  google_fonts : ^6.1.0
  font_awesome_flutter: ^10.7.0
  flutter_screenutil: ^5.7.0
  sizer: ^2.0.15
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  riverpod: ^2.5.0
  flutter_riverpod: ^2.4.9
  image_picker: ^1.0.7
  firebase_messaging: ^14.7.14
flutter_local_notifications: ^16.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/




